#!/bin/bash

# Quick Start Test Script for Hexagonal Strategy Game

echo "=========================================="
echo "  Hexagonal Strategy Game - Quick Test"
echo "=========================================="
echo ""
echo "This script will start the server and two clients for testing."
echo "Make sure you have 3 terminal windows available."
echo ""
echo "Instructions:"
echo "=============="
echo ""
echo "Terminal 1 (Server):"
echo "  cd HexGame"
echo "  ./bin/HexGameServer"
echo ""
echo "Terminal 2 (Player 0):"
echo "  cd HexGame"
echo "  ./bin/HexGameClient"
echo ""
echo "Terminal 3 (Player 1):"
echo "  cd HexGame"
echo "  ./bin/HexGameClient"
echo ""
echo "Game Flow:"
echo "=========="
echo ""
echo "1. CHARACTER SELECTION (both players):"
echo "   - Type: select 0 (Warrior)"
echo "   - Type: select 1 (Mage)"
echo "   - Type: select 2 (Healer)"
echo ""
echo "2. CHARACTER PLACEMENT (both players):"
echo "   Player 0 (LEFT side, q < 0):"
echo "   - Type: place 0 -2 0  (Warrior)"
echo "   - Type: place 1 -2 1  (Mage)"
echo "   - Type: place 2 -2 -1 (Healer)"
echo ""
echo "   Player 1 (RIGHT side, q > 0):"
echo "   - Type: place 0 2 0   (Warrior)"
echo "   - Type: place 1 2 -1  (Mage)"
echo "   - Type: place 2 2 1   (Healer)"
echo ""
echo "3. BATTLE PHASE:"
echo "   View your characters:"
echo "   - Type: view"
echo ""
echo "   Submit actions (example for Player 0):"
echo "   - Type: move p0_c0 -1 0           (Move Warrior forward)"
echo "   - Type: skill p0_c1 fireball 1 0  (Mage attacks)"
echo "   - Type: pass p0_c2                (Healer passes)"
echo "   - Type: ready                     (Lock in turn)"
echo ""
echo "   Wait for opponent to ready, then see results!"
echo ""
echo "Commands Reference:"
echo "==================="
echo "  select <0-5>                  - Select character class"
echo "  place <class> <q> <r>         - Place character"
echo "  move <char_id> <q> <r>        - Move character"
echo "  skill <char_id> <skill> <q> <r> - Use skill"
echo "  pass <char_id>                - Skip action"
echo "  ready                         - Lock turn"
echo "  view                          - Show game state"
echo "  help                          - Show help"
echo "  quit                          - Exit"
echo ""
echo "Character IDs: p0_c0, p0_c1, p0_c2 (Player 0)"
echo "               p1_c0, p1_c1, p1_c2 (Player 1)"
echo ""
echo "Press Enter to continue..."
read

echo "Starting server in background..."
./bin/HexGameServer &
SERVER_PID=$!

sleep 2

echo ""
echo "Server started (PID: $SERVER_PID)"
echo "Now open 2 more terminals and run: ./bin/HexGameClient"
echo ""
echo "Press Ctrl+C to stop the server when done."
echo ""

wait $SERVER_PID
